### ISSUE TITLE
Erro de Access to XMLHttpRequest

### ISSUE THREAD

**Issue by dalzot** [nathanael540/admanager_web#1]
Olá Nathanael, tudo beleza?

Ao tentar utilizar seu package, estou recebendo esse erro no localhost rodando o projeto com `flutter run -d web-server`
Você tem alguma ideia de como solucionar o problema?

Recebo esse erro:

```
registerExtension() from dart:developer is only supported in build/run/test environments where the developer event method hooks have been set by package:dwds v11.1.0 or higher.

[GPT] Error in googletag.display: could not find div with id "ad_3mj4" in DOM for slot: /1122386736/myads/edit-infeed.

Access to XMLHttpRequest at 'https://securepubads.g.doubleclick.net/gampad/ads?pvsid=3965464544820345&correlator=527047119321709......&ga_fc=true' 
from origin 'http://localhost:65523' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

GET https://securepubads.g.doubleclick.net/gampad/ads?pvsid=3965464544820345......&ga_fc=true net::ERR_FAILED 400
```

Se tiver alguma ideia de como solucionar, por favor, fico no aguardo.

**Comment by nathanael540** [comment]
Boa noite, desculpa a demora pela resposta.

Normalmente esse tipo de erro é quando o Google AdManager recusa o domínio e não esta relacionado diretamente com o pacote.

Por favor, faça um teste usando o slot de teste "/6355419/Travel/Europe" com um anuncio de tamanho 300x250.

Se funcionar, sugiro que faça a configuração e um teste utilizando o seu domínio real para que o GAM autorize seu domínio.

**Comment by nathanael540** [comment]
@dalzot Você conseguiu utilizar o pacote? 
Poderia me dar algum retorno? 

Obrigado
