### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by thunderbug1** [nathanael540/admanager_web#4]
Hello, I would like to know if this repo is still being maintained. 
Are you still using this approach to show ads on your app? If not, would you mind sharing what you are using now instead?

**Comment by nathanael540** [comment]
We currently no longer maintain a web version of the application, but I am still willing to maintain this package.

I just checked and it continues to work normally. You can use it, and if necessary, just create a new issue with your request that they will analyze.

REMEMBER: Adsense does not show ads on localhost. Create a Filler item for testing or use a test ID during development.
